# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9  # Latest stable version
    hooks:
      - id: ruff-check
        exclude: "frontend/.*"
        args: [--fix]  # Automatically fix linting issues
      - id: ruff-format
        exclude: "frontend/.*"
